name: publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: '20 4 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: get timestamp
        run: echo "EPOCH=$(date +%s)" >> $GITHUB_ENV
      - name: qemu
        uses: docker/setup-qemu-action@v1
      - name: docker buildx
        uses: docker/setup-buildx-action@v1
      - name: docker hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/minetrack:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/minetrack:${{ env.EPOCH }}
      - name: image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
