name: publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/30 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: prepare buildx
        uses: docker/setup-buildx-action@v1

      - name: docker hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build minetrack
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/minetrack:latest
